HospitalApp/HospitalApp/Areas/Admin/Controllers/ContactsController.cs
using Hospital.Models;
using HospitalApp.DataAccess.Abstract;
using HospitalApp.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HospitalApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ContactsController : Controller
    {
        private IContactRepository _contact;
        private IHospitalInfoRepository _hospitalInfo;

        public ContactsController(IContactRepository contact, IHospitalInfoRepository hospitalInfo)
        {
            _contact = contact;
            _hospitalInfo = hospitalInfo;
        }

        public IActionResult Index()
        {
            return View(_contact.GetAll(IncludeProperties: "Hospital"));
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.hospital = new SelectList(_hospitalInfo.GetAll(), "Id", "Name");

            var contactModel = _contact.GetContactGetById(id);
            return View(contactModel);
        }
        [HttpPost]
        public IActionResult Edit(ContactViewModel cn)
        {
            _contact.UpdateContact(cn);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.hospital = new SelectList(_hospitalInfo.GetAll(), "Id", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Create(ContactViewModel cn)
        {
            _contact.CreateContact(cn);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _contact.DeleteContact(id); 
            return RedirectToAction("Index");
        }
    }
    }

    

HospitalApp/HospitalApp/Areas/Admin/Controllers/DepartmentsController.cs
using Hospital.Models;
using HospitalApp.DataAccess.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace HospitalApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DepartmentsController : Controller
    {
        private IDepartmentRepository _department;

        public DepartmentsController(IDepartmentRepository department)
        {
            _department = department;
        }
        public IActionResult Index()
        {
            return View(_department.GetAll(IncludeProperties: "Hospital"));
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var departmentModel = _department.GetDepartmentById(id);
            return View(departmentModel);
        }
        [HttpPost]
        public IActionResult Edit(DepartmentViewModel dp)
        {
            _department.UpdateDepartment(dp);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(DepartmentViewModel dp)
        {
            _department.CreateDepartment(dp);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _department.DeleteDepartment(id);
            return RedirectToAction("Index");
        }
    }
}

HospitalApp/HospitalApp/Areas/Admin/Controllers/HospitalsController.cs
using Hospital.Models;
using HospitalApp.DataAccess.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace HospitalApp.Areas.Admin.Controllers
{
    
    [Area("Admin")]
    public class HospitalsController : Controller
    {
        private IHospitalInfoRepository _hospitalInfo;

        public HospitalsController(IHospitalInfoRepository hospitalInfo)
        {
            _hospitalInfo = hospitalInfo;
        }

        public IActionResult Index()
        {
            return View(_hospitalInfo.GetAll());
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var hospitalModel = _hospitalInfo.GetHospitalById(id);
            return View(hospitalModel);
        }
        [HttpPost]
        public IActionResult Edit(HospitalViewModel hp)
        {
            _hospitalInfo.UpdateHospital(hp);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(HospitalViewModel hp)
        {
            _hospitalInfo.CreateHospital(hp);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _hospitalInfo.DeleteHospital(id);
            return RedirectToAction("Index");
        }
    }
}

HospitalApp/HospitalApp/Areas/Admin/Controllers/RoomsController.cs
using Hospital.Models;
using HospitalApp.DataAccess.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace HospitalApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoomsController : Controller
    {
        private IRoomRepository _room;

        public RoomsController(IRoomRepository room)
        {
            _room = room;
        }
        public IActionResult Index()
        {
            return View(_room.GetAll(IncludeProperties:"Hospital"));
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var roomModel = _room.GetRoomById(id);
            return View(roomModel); 
        }
        [HttpPost]
        public IActionResult Edit(RoomViewModel rm)
        {
            _room.UpdateRoom(rm);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(RoomViewModel rm)
        {
            _room.CreateRoom(rm);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _room.DeleteRoom(id);
            return RedirectToAction("Index");
        }
    }
    }

HospitalApp/HospitalApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Style.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HospitalApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Hospitals" asp-action="Index">Hospital</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Rooms" asp-action="Index">Room</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Contacts" asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Departments" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Appointments" asp-action="Index">Appointments</a>
                            </li>
                        <li class="nav-item">
                            <a id="doctor-register" class="nav-link text-dark" asp-area="Identity" asp-page="/Account/DoctorRegister">Doctor</a>
                        </li>
                        <li class="nav-item">
                            <a id="patient-register" class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/PatientRegister">Patient</a>
                        </li>
                    </ul>
                    
                    <partial name ="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>